default_stages: [ commit, push ]
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
        args: [ --allow-multiple-documents, --unsafe ]
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^.*\.(md|rst)$
      - id: mixed-line-ending
      - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [
          --line-length=120,
          --target-version=py310
        ]
        exclude: ^(venv/|docs/)
        types: [ 'python' ]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ --profile=black ]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        verbose: true
        args:
          [
            --max-line-length=120,
            --fail-under=8,
            --fail-on=E
          ]
