#!/usr/bin/bash
PORT=9049

# Enable opening multiple files
ulimit -n 4096

# Enable to save bigger files
ulimit -f unlimited

# Enable more threads per process by increasing virtual memory (https://stackoverflow.com/questions/344203/maximum-number-of-threads-per-process-in-linux)
ulimit -v unlimited

export OMP_NUM_THREADS=16

# Check if port is already in use
if lsof -Pi :$PORT -sTCP:LISTEN -t >/dev/null ; then
    echo "Port $PORT is already in use. Port forwarding is already running."
else
    # Start port forwarding
    ssh -N -D $PORT pcspeech4 &
    echo "Port forwarding started on port $PORT."
fi
export http_proxy=socks5://localhost:$PORT
export https_proxy=socks5://localhost:$PORT

# if more than one device is passed, use torchrun to run the script
if [ "$N_GPUS" -gt 1 ]; then
  torchrun --standalone --nnodes=1 --nproc-per-node=$N_GPUS "$@"
else
  python "$@"
fi
